package ch.bfh.btx8081.w2017.green.Spero.persistence;

import java.io.Serializable;
import java.time.LocalDate;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import ch.bfh.btx8081.w2017.green.Spero.interfaceEnum.Mood;

/**
 * 
 * @author SoKeY
 * 
 * We work with JPA
 * This class represent one Entry of a Diary.
 * This class is an Entity
 * 
 *
 */

@Entity
public class DiaryEntry implements Serializable {
	private static final long serialVersionUID = 1L;
	
	/**
	 * An Entry consists of 
 * a Diary Entry Number : serial
 * a Title : String
 * a Text : String
 * a Tag : String
 * and a Parameter of the actual Mood : Mood (Enumeration)
	 */

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	private int diaryEntryNumber;
	private String diaryTitle;
	private String diaryText;
	private String tag;
	private Mood moodParam;
	
//	private LocalDate date;

	public DiaryEntry() {

	}

	/**
	 * Constructor, which will be called by the Diary Model
	 * 
	 * @param diaryTitle
	 * @param diaryText
	 * @param moodParam
	 */
	public DiaryEntry(String diaryTitle, String diaryText, Mood moodParam) {
		this.diaryTitle = diaryTitle;
		this.diaryText = diaryText;
		this.moodParam = moodParam;

	//	 this.date = LocalDate.now();
	}
	
	/*
	 * Setters and Getters generated by Exclipse
	 */

	public void setDiaryEntryNumber(int diaryEntryNumber) {
		this.diaryEntryNumber = diaryEntryNumber;
	}

	public void setMoodparam(Mood mood) {
		this.moodParam = mood;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public void setText(String text) {
		this.diaryText = text;
	}

	public void setTitle(String title) {
		this.diaryTitle = title;
	}

	public int getDiaryEntryNumber() {
		return this.diaryEntryNumber;
	}

	public Mood getMoodparam() {
		return this.moodParam;
	}

	public String getTag() {
		return this.tag;
	}

	public String getText() {
		return this.diaryText;
	}

	public String getTitle() {
		return this.diaryTitle;
	}

//	public LocalDate getDate() {
//		return date;
//	}
//
//	public void setDate(LocalDate date) {
//		this.date = date;
//	}
//	
	
}
